"use client";
import { useState } from "react";
import { req } from "@/lib/api";
type Person = {id:string;name:string;description:string;memories:number};
type Preview = {markdown?:string;title:string;basis:string;source_note:string;events:number;characters:Person[];story?:{events:{id:string;title:string;stage:string;text:string;viewpoints:{character_id:string;knowledge:string;memory:string;quote:string}[]}[]}};
const button="min-h-10 rounded-xl border border-zinc-200 bg-white px-4 text-sm hover:bg-zinc-50 disabled:opacity-40";
export function StoryImport({onImported}:{onImported:(id:string)=>Promise<void>}) {
  const [text,setText]=useState("");const [preview,setPreview]=useState<Preview|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function run(save:boolean){setBusy(true);setError("");try{if(save){const result=await req<{document_id:string}>("/api/stories/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,confirmed:true})});await onImported(result.document_id);setText("");setPreview(null);}else{setPreview(await req<Preview>("/api/stories/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})}));}}catch(e){setError(String(e));}finally{setBusy(false);}}
  return <details className="my-5 rounded-2xl border border-zinc-200 bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">导入故事文档 · 预览后确认</summary><p className="mt-3 text-xs leading-6 text-zinc-500">先和故事文档助手讨论需求，确认设定与正文后，在这里粘贴它生成的结构化文档，或选择保存的 JSON / Markdown。导入保存故事事件与人物知情依据，再为选中的人物建立专属记忆。</p>
    <input aria-label="选择故事文档文件" type="file" accept=".json,.md,.txt" disabled={busy} className="mt-3 text-sm" onChange={async e=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;if(f.size>2000000){setError("文档不能超过 2 MB");return;}setText(await f.text());setPreview(null);}} />
    <textarea aria-label="结构化故事文档" className="mt-3 min-h-48 w-full rounded-xl border border-zinc-200 p-3 font-mono text-xs" placeholder="粘贴故事助手生成的 personal-ai-story-v1 文档" disabled={busy} value={text} maxLength={2000000} onChange={e=>{setText(e.target.value);setPreview(null);}} />
    <button className={button} disabled={busy||!text.trim()} onClick={()=>void run(false)}>{busy?"处理中…":"检查并预览世界书"}</button>
    {error&&<p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}
    {preview&&<div className="mt-4 space-y-3"><h3 className="font-semibold">{preview.title}</h3><p className="text-sm">{({original:"原创",source_based:"资料整理",adaptation:"改编"})[preview.basis as "original"]} · {preview.characters.length} 个人物 · {preview.events} 个事件</p><p className="text-sm text-zinc-500">{preview.source_note}</p><div className="max-h-96 space-y-3 overflow-auto">{preview.story?.events.map(event=><details key={event.id} className="rounded-xl border border-zinc-200 p-3"><summary className="cursor-pointer text-sm">{event.stage} / {event.title}</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{event.text}</p>{event.viewpoints.map(v=><p key={v.character_id} className="mt-2 border-t border-zinc-100 pt-2 text-xs leading-6">{preview.characters.find(p=>p.id===v.character_id)?.name} · {v.knowledge}：{v.memory||"不知道，不生成记忆"}<br/>依据：{v.quote||"无"}</p>)}</details>)}</div><p className="text-xs leading-6 text-zinc-500">请核对故事内容、人物与知情范围。确认只导入世界书，选择人物后才创建角色。所选在线检索模型可能接收正文用于生成向量。</p><button className={`${button} mr-2`} disabled={!preview.markdown} onClick={()=>{const url=URL.createObjectURL(new Blob([preview.markdown || ""],{type:"text/markdown;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=preview.title.replace(/[\\/:*?"<>|]/g,"_")+".md";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>下载世界书文档</button><button className={`${button} bg-zinc-900 text-white hover:bg-zinc-700`} disabled={busy} onClick={()=>void run(true)}>内容确认无误，导入世界书</button></div>}
  </details>;
}
export { default as StoryCharacters } from "./StoryCharacterPicker";
