"use client";
import { useEffect, useState } from "react";
import { req, fetchDocuments, type KnowledgeDocument } from "@/lib/api";

type Job = { id:string;title:string;status:string;running:boolean;completed:number;total:number;output_path:string;error:string;document_id?:string;files:string[];plan:{chapters?:{title:string;scope:string;sources_needed:string}[]};report:{narrative_chars?:number;events?:number;issues?:string[]} };
type Folder = {current_path:string;parent_path:string|null;directories:{name:string;path:string}[]};
const button="rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm hover:bg-zinc-50 disabled:opacity-40";
const labels:Record<string,string>={pending:"等待规划",planning:"规划中",awaiting_plan:"等待确认大纲",writing:"逐章生成中",paused:"已暂停，可继续",failed:"未完成，可继续",review:"草稿已保存，待核对",imported:"已导入知识库"};
export default function WorldbookWorkshop({conversationId,onImported}:{conversationId?:string|null;onImported?:()=>void}){
 const [research,setResearch]=useState("");
 const [open,setOpen]=useState(false),[brief,setBrief]=useState(""),[directory,setDirectory]=useState(""),[count,setCount]=useState(12),[minimum,setMinimum]=useState(800),[jobs,setJobs]=useState<Job[]>([]),[documents,setDocuments]=useState<KnowledgeDocument[]>([]),[sources,setSources]=useState<string[]>([]),[folder,setFolder]=useState<Folder|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function refresh(){const data=await req<{default_output_dir:string;jobs:Job[]}>("/api/story-builds");setJobs(data.jobs);setDirectory(v=>v||localStorage.getItem("story.output.directory")||data.default_output_dir);}
 useEffect(()=>{if(!open)return;let stale=false;const load=async()=>{try{const data=await req<{default_output_dir:string;jobs:Job[]}>("/api/story-builds");if(!stale){setJobs(data.jobs);setDirectory(v=>v||localStorage.getItem("story.output.directory")||data.default_output_dir);}}catch(e){if(!stale)setError(String(e));}};void load();void fetchDocuments().then(v=>{if(!stale)setDocuments(v);});const t=setInterval(()=>void load(),2000);return()=>{stale=true;clearInterval(t);};},[open]);
 async function action(work:()=>Promise<unknown>){setBusy(true);setError("");try{await work();await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function browse(path?:string){setFolder(await req<Folder>("/api/settings/directories"+(path?"?path="+encodeURIComponent(path):"")));}
 return <><button type="button" className={button} onClick={()=>setOpen(true)}>世界书工坊 · 生成与保存</button>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><section role="dialog" aria-modal="true" aria-label="世界书工坊" className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">世界书工坊</h2><button className={button} onClick={()=>setOpen(false)}>关闭</button></div><p className="my-3 text-sm text-zinc-500">先规划并确认大纲，再逐章生成。完成章节会保存到磁盘；关闭此窗口不停止任务。正文与角色卡完成后由你确认导入。</p>
 <label className="block text-sm font-medium">文档生成位置</label><div className="my-2 flex gap-2"><input aria-label="文档生成位置" className="min-w-0 flex-1 rounded-xl border p-2 text-sm" value={directory} onChange={e=>setDirectory(e.target.value)}/><button className={button} onClick={()=>void action(()=>browse())}>选择文件夹</button></div><p className="text-xs text-zinc-500">每个任务建立独立的 worldbook-ID 文件夹，不覆盖已有文件。</p>
 {folder&&<div className="my-3 rounded-xl border p-3"><p className="break-all text-xs">{folder.current_path}</p><div className="my-2 flex gap-2">{folder.parent_path&&<button className={button} onClick={()=>void action(()=>browse(folder.parent_path!))}>上一级</button>}<button className={button} onClick={()=>{setDirectory(folder.current_path);localStorage.setItem("story.output.directory",folder.current_path);setFolder(null);}}>使用此文件夹</button></div><div className="max-h-40 overflow-auto">{folder.directories.map(d=><button key={d.path} className="block w-full p-2 text-left text-sm hover:bg-zinc-50" onClick={()=>void action(()=>browse(d.path))}>{d.name}</button>)}</div></div>}
 <div className="mt-4 flex items-center justify-between"><label className="text-sm font-medium">确认后的需求、范围与来源说明</label>{conversationId&&<button className={button} onClick={()=>void action(async()=>{const r=await req<{brief:string;truncated:boolean}>(`/api/story-builds/brief/${conversationId}`);setBrief(r.brief);if(r.truncated)setError("仅载入最近部分对话，请补充缺少的早期设定后再生成。");})}>从本次聊天载入</button>}</div><textarea aria-label="世界书生成需求" value={brief} onChange={e=>setBrief(e.target.value)} maxLength={16000} className="my-2 min-h-36 w-full rounded-xl border p-3 text-sm" placeholder="作品/原创设定、覆盖范围、人物、已确认的偏好、需要的细节与资料依据。不要把提纲当作完整正文。"/>
 <div className="flex flex-wrap gap-4 text-sm"><label>章节数 <input type="number" min={2} max={30} value={count} onChange={e=>setCount(Number(e.target.value))} className="w-20 rounded border p-2"/></label><label>每章最少正文字符 <input type="number" min={400} max={2500} value={minimum} onChange={e=>setMinimum(Number(e.target.value))} className="w-24 rounded border p-2"/></label><span className="self-center text-zinc-500">目标至少 {count*minimum} 字符，不计 JSON 和重复视角</span></div>
 <label className="mt-3 block text-sm">联网核实关键词（可选，填写公开作品名与范围）<input aria-label="联网核实关键词" value={research} onChange={e=>setResearch(e.target.value)} maxLength={200} className="mt-2 w-full rounded-xl border p-2" placeholder="例如：孤独摇滚 动画第一季 官方故事；留空不联网" /></label><p className="mt-1 text-xs text-zinc-500">需在联网设置开启 Tavily。仅发送关键词和章节标题，搜索来源会随章节保存。</p>
 <details className="my-3 text-sm"><summary>选择已有资料（{sources.length}）</summary>{documents.filter(d=>d.status==="indexed").map(d=><label key={d.id} className="my-2 flex gap-2"><input type="checkbox" checked={sources.includes(d.id)} onChange={e=>setSources(v=>e.target.checked?[...v,d.id]:v.filter(id=>id!==d.id))}/>{d.original_filename}</label>)}</details>
 <button disabled={busy||brief.trim().length<20||jobs.some(j=>j.running)} className={button} onClick={()=>void action(async()=>{localStorage.setItem("story.output.directory",directory);await req("/api/story-builds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brief,output_dir:directory,chapter_count:count,min_chapter_chars:minimum,document_ids:sources,research_query:research})});})}>创建任务并生成大纲</button><p className="mt-2 text-xs text-zinc-500">使用当前默认聊天模型，云端模型会接收需求和所选资料片段并产生调用费用。资料不足会停止提示，不会为凑字数编造原作。</p>
 {error&&<p role="alert" className="my-3 text-sm text-red-600">{error}</p>}
 <div className="mt-6 space-y-4">{jobs.map(job=><article key={job.id} className="rounded-xl border p-4"><h3 className="font-semibold">{job.title}</h3><p className="my-2 text-sm">{labels[job.status]||job.status} · {job.completed}/{job.total} 章 · 正文 {job.report.narrative_chars||0} 字符 · {job.report.events||0} 个事件</p><p className="break-all text-xs text-zinc-500">实际保存目录：{job.output_path}</p>{job.error&&<p className="mt-2 text-sm text-red-600">{job.error}</p>}
 {job.plan.chapters&&<details className="my-3 text-sm" open={job.status==="awaiting_plan"}><summary>章节规划</summary>{job.plan.chapters.map((c,i)=><div key={i} className="my-2 border-l pl-3"><b>{i+1}. {c.title}</b><p>{c.scope}</p>{c.sources_needed&&<p className="text-zinc-500">待核实：{c.sources_needed}</p>}</div>)}</details>}
 {job.report.issues?.map((issue,i)=><p key={i} className="my-1 text-xs text-amber-700">{issue}</p>)}<div className="my-3 flex flex-wrap gap-2">{job.files.map(name=><a key={name} className={button} href={`/api/story-builds/${job.id}/files/${encodeURIComponent(name)}`} target="_blank" rel="noreferrer">{name}</a>)}</div><div className="flex gap-2">{job.running?<button disabled={busy} className={button} onClick={()=>void action(()=>req(`/api/story-builds/${job.id}/stop`,{method:"POST"}))}>停止，保留进度</button>:!["review","imported"].includes(job.status)&&<button disabled={busy} className={button} onClick={()=>void action(()=>req(`/api/story-builds/${job.id}/continue`,{method:"POST"}))}>{job.status==="awaiting_plan"?"确认大纲，开始逐章生成":"继续未完成章节"}</button>}{job.status==="review"&&<button disabled={busy} className={button} onClick={()=>{if(window.confirm("已阅读生成文件和质量提示，确认导入知识库？"))void action(async()=>{const r=await req<{document_id:string}>(`/api/story-builds/${job.id}/import`,{method:"POST"});localStorage.setItem("story.library.document",r.document_id);onImported?.();});}}>确认内容，导入知识库</button>}</div></article>)}</div></section></div>}</>;
}

